# Uses CyberArk AIM Central Credential Provider Secret Lookup
- hosts: localhost
  gather_facts: no
  vars:
    ami_id: ami-0c322300a1dd5dc79
    keypair: cyberark-pasaas
    region: us-east-1
    security_group: sg-035eb1a11c4584d01
    subnet: subnet-08f9e42a174453e28
    type: t2.micro

  tasks:
    - name: Start RHEL 8 AWS EC2 Instance
      ec2:
        assign_public_ip: yes
        group_id: "{{ security_group }}"
        image: "{{ ami_id }}"
        instance_tags:
          Name: RHEL Client
          role: client_rhel
        instance_type: "{{ type }}"
        key_name: "{{ keypair }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet }}"